### PR TITLE
Add Python choose your own adventure (aka PYOA) framework

### PR DESCRIPTION
**Pull request by dastels**

### CODE REVIEW

**Comment by kattni** [comment]
@dastels Please do a release on the library before submitting to the bundle, the build will fail otherwise. Thanks!

**Comment by kattni** [comment]
I restarted the build and it's still failing on no release, when there has apparently been a release. Not sure what's going on.

**Comment by siddacious** [comment]
@kattni If you look at the exact failure, it's looking for a tag/release at commit `f0a92` which indeed does not have a release because it's an earlier commit, likely not coincidentally when Limor merged Dave's addition of a `travis.yml`:
https://github.com/adafruit/Adafruit_CircuitPython_PYOA/commit/f0a920d2b645353652a55917d2e98a46cf71b65b

Not sure why it's stuck looking for a release tag on that commit, but that's why it's failing

**Comment by siddacious** [comment]
@kattni Looked a little closer and if you take a look at the diffs, you can see that the submodule was added at the above commit before a release. I think the easiest way to handle this would be to start over and add the submodule again now that there is a release

**Comment by kattni** [comment]
@siddacious Good catch. I noticed the commit hash but didn't look further into it. 

@dastels Please resubmit the lib to the bundle. Thank you. We can close this once you have done so.

**Comment by ladyada** [comment]
@dastels ok do you know the process for next time you submit a library or do ya need assistance?

**Comment by dastels** [comment]
Yeah... don't add to the bundle until the end :)  Question: will subsequent release be automatically picked up in the bundle or does the submodule need to be refreshed?

**Comment by ladyada** [comment]
the submodule is auto-checked daily, just do a proper semver release to get it picked up for next day

**Pull request merged**
