### PR TITLE
Add Adafruit_CircuitPython_DHTlib to bundle

### PR DESCRIPTION
**Pull request by mrmcwethy**
I think this should do it, but there seems to more changes than i expected.  One of these days i will get the hang of GIT.  The only real changes are to the .gitmodule file.

### CODE REVIEW

**Comment by mrmcwethy** [comment]
@tannewt  can you take a look at this and let me know your comment.  Adding Adafruit_CircuitPython_DHTlib to bundle

**Comment by tannewt** [comment]
The second commit looks good! The extra stuff looks like you need to run `git submodule update`. After selecting a new branch, the submodules are not updated and need to updated separately. Ping me on discord if you need help git wrangling.

**Comment by mrmcwethy** [comment]
@tannewt I did the rebase and git push --force.  That cleaned it up.

**Comment by mrmcwethy** [comment]
@tannewt i renamed and tested the build-bundles.py and resultant .mpy file.

**Comment by tannewt** [comment]
Thank you so much @mrmcwethy !

**Pull request merged**
