### PR TITLE
Exclude alpha and beta releases

### LINKED ISSUE #173: Don't include alpha or beta releases in bundle
I'd like to publish a beta version of a library as a pre-release. It should not be in the bundle.

We could query github to find the latest release that is not a pre-release, or we could go by tag. A alpha or beta release tag will contain a `-`, like `3.0.0-beta.0`. Regular release tags don't contain a `-`.

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #173.

Thanks to @sommersoft for working on this with me. It took a lot of trial and error to figure out the right `git rev-list` arguments.

### CODE REVIEW

**Comment by dhalbert** [comment]
@sommersoft - Aha, I had trouble finding it! Is this still a useful change? I'm not sure when this scripts gets run anymore (maybe never).

**Comment by sommersoft** [comment]
I get the feeling that it was the initial bundler/updater, before @tannewt setup Adabot. I don't know of it being used anywhere...

**Comment by tannewt** [comment]
Can we close this?

**Comment by dhalbert** [comment]
How about merging this anyway to keep it the same as adabot?

**Pull request merged**
