### PR TITLE
Added documentation links to circuitpython_library_list.md.

### PR DESCRIPTION
**Pull request by woolseyj**
Updated circuitpython_library_list.md to include links to the readthedocs documentation for all of the libraries.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Woohoo! Nice work! Thank you so much.

**Comment by woolseyj** [comment]
@tannewt, I saw that the pull request was merged and the documentation links were added to the file (thank you), but it appears that an automated Adabot update wiped out those changes.

**Comment by tannewt** [comment]
Oh no! I thought it was a manually edited file.

**Comment by tannewt** [comment]
Looks like it is auto-generated: https://github.com/adafruit/adabot/blob/2d5a6d955be725f9769b1e12645735147f3595d1/adabot/circuitpython_bundle.py#L59-L103

Sorry about that!

**Comment by woolseyj** [comment]
So will someone be updating the Adabot auto update program?

**Comment by tannewt** [comment]
Ya, I'll take a crack at it.

**Pull request merged**
