### PR TITLE
Add SI1145

### PR DESCRIPTION
**Pull request by caternuson**
Adds entry for SI1145 library.

### CODE REVIEW

**Review by tekktrik — CHANGES_REQUESTED** [review]
It looks like the module is in `.gitmodules` but not in `libraries/`

**Review by tekktrik — APPROVED** [review]
Sweeto!

**Review by tekktrik — CHANGES_REQUESTED** [review]
Actually, looks like an inital release is needed, I believe

**Comment by caternuson** [comment]
Made an initial release:
https://github.com/adafruit/Adafruit_CircuitPython_SI1145/releases/tag/1.0.0

**Comment by caternuson** [comment]
Also restarted the CI run. Looks like it passed now.

**Review by tekktrik — APPROVED** [review]
Woo!

**Pull request merged**
