### PR TITLE
RFC: Library Listing

### PR DESCRIPTION
**Pull request by sommersoft**
@kattni, @ptorrone 

Requesting comments on adding a library listing page, formatting of the list, and information desired. The two example listings included were generated by Adabot (local code for now). 

To further test Adabot updating the file automagically, it will be best to have the file in the repo already, which is another end goal of this PR.

Current examples are done in Markdown. Lists are currently categorized by "Drivers" and "Helpers". 
Links to both the GitHub repo, and PyPi (if available) are included.

- [Standard Unordered List Quick View](https://github.com/sommersoft/Adafruit_CircuitPython_Bundle/blob/library_list/circuitpython_library_list_unordered_version.md)
- [Tabulated List Quick View](https://github.com/sommersoft/Adafruit_CircuitPython_Bundle/blob/library_list/circuitpython_library_list_table_version.md)

_Note: please don't merge until some final decisions have been made. At that point, I'll replace these two files with the single, more aptly named file._

### CODE REVIEW

**Comment by kattni** [comment]
Looks good! Thanks for submitting these options. This is a great place to start!

**Comment by ptorrone** [comment]
hi hi, thanks for this @sommersoft and @kattni - let's go with the "Standard Unordered List Quick View" (https://github.com/sommersoft/Adafruit_CircuitPython_Bundle/blob/library_list/circuitpython_library_list_unordered_version.md) and please add this image in there at the top :)

here is where it lives on github now...
https://raw.githubusercontent.com/adafruit/circuitpython-weekly-newsletter/gh-pages/assets/22_1023blinka.png

and attached:

22_1023blinka

**Comment by ptorrone** [comment]
@sommersoft and @kattni feel free to add the "count" if ya want since we use that each week in the newsletter now, i think ya'll do that in another way, but if it makes sense add it here. i count 105 total.

oh, also the last one in libs is missing... it just has a dot, but viewing it says  https://github.com/adafruit/Adafruit_CircuitPython_NeoTrellis

**Comment by ptorrone** [comment]
aaand last up, this was my test to see how fast i could make a blog post from github markdown to html to this ... about a min, so all good :) https://blog.adafruit.com/2018/10/25/adafruit-circuitpython-libraries-there-are-104-at-this-time-circuitpython-adafruit-adafruit/

**Comment by kattni** [comment]
Excellent! 🌮

**Comment by sommersoft** [comment]
> oh, also the last one in libs is missing.
yeah, I almost put in a fix for that earlier, but its a great test for upcoming adabot updating.

Mirrored your blog post format, and added an auto count: https://github.com/sommersoft/Adafruit_CircuitPython_Bundle/blob/library_list/circuitpython_library_list.md

**Comment by sommersoft** [comment]
Oh...and if you'd rather this be HTML @ptorrone, that is totally doable. There's what...only 4 different elements in use?

**Comment by ptorrone** [comment]
@sommersoft naa, let's keep it as it (markdown), all good

**Pull request merged**
