### PR TITLE
adding VCNL4200 library

### PR DESCRIPTION
**Pull request by BlitzCityDIY**
@FoamyGuy - could you also add it to the circuitpython subproject on readthedocs?

### CODE REVIEW

**Review by FoamyGuy — APPROVED** [review]
thank you! yes, I'll add it as a subproject on RTD.

**Comment by FoamyGuy** [comment]
@BlitzCityDIY actually looking in RTD now I think I can only add subprojects that I am a maintainer of. I log in as myself (foamyguy) on RTD not adabot. 

I have access to add subprojects but it only gives me a dropdown to choose from ones that I am maintainer on. 

If you can add me to VCNL4200 as a maintainer I can add it otherwise I think you or adabot account has to be the one to add as subproject.

**Comment by BlitzCityDIY** [comment]
@FoamyGuy ah okay, just added you

**Comment by FoamyGuy** [comment]
Thank you. That is added now and the docs link in the readme is active :tada:

**Comment by BlitzCityDIY** [comment]
yay, thank you! 🎉

**Pull request merged**
