### PR TITLE
added driver for TSL2561

### PR DESCRIPTION
**Pull request by caternuson**
what it says

### CODE REVIEW

**Comment by ladyada** [comment]
do you mind if we make some tweaks to the TSL2561 library to make it more memory-efficient? :)

**Comment by caternuson** [comment]
not at all, but would like to know the where and how

**Comment by ladyada** [comment]
ok ill open up issues ~there~ with suggestions!

**Comment by tannewt** [comment]
Please rebase this. Other modules have been updated/added since this pull was requested.

**Comment by caternuson** [comment]
OK. Trying to rebase. What am I doing wrong? Here's what I did:

make local copy of my branch:
```
git clone https://github.com/caternuson/Adafruit_CircuitPython_Bundle.git
```
add upstream remote:
```
cd Adafruit_CircuitPython_Bundle
git remote add upstream https://github.com/adafruit/Adafruit_CircuitPython_Bundle.git
```
fetch upstream:
```
git fetch upstream
```
try to rebase:
```
git rebase upstream/master
```
*FAIL* due to conflict in .gitmodule
fix with text editor
commit changes:
```
git add .
git commit -m "resolved rebase conflict"
```
try to continue with rebase:
```
git rebase --continue
```
acts like there's nothing to do:

> Applying: added driver for TSL2561
> No changes - did you forget to use 'git add'?
> If there is nothing left to stage, chances are that something else
> already introduced the same changes; you might want to skip this patch.
> 
> When you have resolved this problem, run "git rebase --continue".
> If you prefer to skip this patch, run "git rebase --skip" instead.
> To check out the original branch and stop rebasing, run "git rebase --abort".

**Comment by tannewt** [comment]
`git rebase --continue` does the commit on your behalf so don't do it yourself.

**Comment by caternuson** [comment]
That's what I did initially, but got this which made me think I need to add/commit:

> .gitmodules: needs merge
> You must edit all merge conflicts and then
> mark them as resolved using git add

**Comment by tannewt** [comment]
You just need to add and then continue. No commit

**Comment by caternuson** [comment]
Ohhhh. Add but don't commit. Got it. That worked.

**Comment by caternuson** [comment]
OK. Now having issues pushing up changes:
```
git push origin master
```
> To https://github.com/caternuson/Adafruit_CircuitPython_Bundle.git
>  ! [rejected]        master -> master (non-fast-forward)
> error: failed to push some refs to 'https://github.com/caternuson/Adafruit_CircuitPython_Bundle.git'
> hint: Updates were rejected because the tip of your current branch is behind
> hint: its remote counterpart. Integrate the remote changes (e.g.
> hint: 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
>

**Comment by tannewt** [comment]
Use the `--force` or `--force-with-lease` to be nice.

**Comment by caternuson** [comment]
Well, that worked. Why was that necessary?

**Comment by tannewt** [comment]
Force is necessary when you rebase because you aren't simply adding another commit. You are actually replacing some commits with others.

No need for a new PR. PRs are based on the branch which you just updated. :-)

**Pull request merged**
