### PR TITLE
Adding HUSB238

### PR DESCRIPTION
**Pull request by BlitzCityDIY**
Adding the HUSB238 library. If someone with access to ReadTheDocs is able to accept the adabot invite and add to the CircuitPython project I'd appreciate it 🙂

### CODE REVIEW

**Comment by tannewt** [comment]
Accepted and added as a subproject.

**Review by tannewt — CHANGES_REQUESTED** [review]
There should be a third file added for the folder of the library itself.

**Comment by BlitzCityDIY** [comment]
@tannewt thanks! sorry about that, forgot to submodule 🤦‍♀️

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
