### PR TITLE
Fix issued #23 - Add CharLCD Driver

### PR DESCRIPTION
**Pull request by 3mp3ri0r**
Hope it help.

### CODE REVIEW

**Comment by tannewt** [comment]
Hi @3mp3ri0r thank you for picking these up! Could you please remove the DHT commit because its already been added to the bundle. Thanks!

**Comment by 3mp3ri0r** [comment]
Okay @tannewt. Did I already fix DHT commit problem?

**Comment by tannewt** [comment]
Looks like its still in this pull request. There are instructions on removing one commit here: https://superuser.com/questions/35267/how-can-i-roll-back-1-commit and then you'll need to `git push --force` to update the copy on github.

**Comment by mrmcwethy** [comment]
@3mp3ri0r we would love to get the CharLCD library released to the Adafruit bundle.  Can you take a few minutes and correct the pull request?

**Comment by tannewt** [comment]
@mrmcwethy feel free to pick this up. Seems like @3mp3ri0r is busy.

**Comment by mrmcwethy** [comment]
I tested the Adafruit_Circuitpython_CharLCD library on a 1602 LCD module and also took a close look at the library code.  I noticed a few things:

1. __init__.py forces both .py class files to be included.  Should the __init__.py file import two class definitions when only one of them will be used at one time.
2. the documented class signature for Character_LCD includes an optional backlight feature which is labeled TODO.  At minimum the class documentation should be updated.  I will test the feature.
3. the monochrome and rgb classes have a lot of code in common but the approach was to copy/paste this common code.  There must have been a good reason for this, my natural tendency would be to create a base case and derived classes.  Any history here?

Thoughts on the above, anyone?

**Comment by ladyada** [comment]
@tdicola did the most recent revision of the code - and will be able to answer these questions best! adding to thread :)

**Comment by mrmcwethy** [comment]
This pull request is now obsolete as a result of another one.  I will close it now

**Pull request closed without merging**
